### PR TITLE
Add a coverage report link to Trac

### PR DESCRIPTION
**Pull request by hawkowl**

### CODE REVIEW

**Comment by hawkowl** [comment]
cc @adiroiban @glyph

**Comment by glyph** [comment]
How would I test this with the VM?

**Comment by hawkowl** [comment]
The instructions from https://github.com/twisted-infra/braid/pull/111#issuecomment-138052006 and the next comment would work, probably. (Or is this  a hint to write these in a place in the repo? ;) )

**Comment by glyph** [comment]
Definitely writing them somewhere near something that looked like documentation would be progress.  But it was genuine curiosity in this case, not a hint.

**Comment by adiroiban** [comment]
Any progress on this?

I think the coverage links will be of great help.

Can we also have a link to the whole branch, not only on the diff?

Can we have the author + lp bugs fields removed?

Thanks!

**Comment by adiroiban** [comment]
For the documentation part, maybe we can update the README file inside the trac service folder with info about how to test it and that are the dependencies.

Thanks!

**Pull request merged**
