### PR TITLE
Remove unused steps

### PR DESCRIPTION
**Pull request by rodrigc**
More of the logic here has moved into tox steps,
so this stuff is unused and can go.

### CODE REVIEW

**Comment by rodrigc** [comment]
Doesn't hurt to keep this around

**Comment by tomprince** [comment]
That is what version control is for.

**Comment by rodrigc** [comment]
@tomprince I don't understand your feedback.

**Comment by tomprince** [comment]
There is no point in keeping dead code around when you have version control, since if you need it, you can always get from history. So, if this code is dead, it should be removed.

Also, having it around is potentially confusing for people looking at the code, as they would expect that it is there for a reason, rather than just being a historical artifact.

**Comment by glyph** [comment]
A really good article on this topic: https://nedbatchelder.com/text/deleting-code.html

**Pull request closed without merging**
