### PR TITLE
Use virtualenvs, not pip --user

### PR DESCRIPTION
**Pull request by hawkowl**

### CODE REVIEW

**Comment by hawkowl** [comment]
cc @adiroiban for review, there's more to follow but this is a prerequisite

**Comment by adiroiban** [comment]
Thanks for the update.

Is this part of #163?
Why we need this?

How can I test these changes?

**Comment by hawkowl** [comment]
This is a part of #163, part of the #179 PR. It makes virtualenvs instead of using `pip --user`, so that system dependencies (like Twisted) are easier to update, and fixes #1 and #4. It makes the Buildbot work easier (recent pips cache downloaded packages, so having a virtualenv with its own pip makes it much nicer for installing and testing).

You can test it just by installing some of the altered services (note: this does not include trac or buildbot, which are modified to use it later) and starting them -- `amptrac.install` should test it out nicely.

**Comment by adiroiban** [comment]
why not merge this in master ?  What is specific to git migration in this branch?

I don't know how this is part of #163 as it is not described there.

Thanks

**Comment by hawkowl** [comment]
We can't merge it to master, as it will break everything :)

This is not so much a thing unto itself, but it is a logical separation of the work that was needed to get Buildbot and Trac testable, so that it's reviewable without the baggage of those changes.

**Comment by hawkowl** [comment]
Will be superceded by new PR.

**Pull request closed without merging**
