### PR TITLE
[DO NOT MERGE] Migrate to Git, Infrastructure Changes

### PR DESCRIPTION
**Pull request by hawkowl**
Things this does:

- Migrates Trac to use trac-github.
- Migrates Buildbot to Nine, and using GitHub. It has a 'twisted view' which is similar to the old Boxes view, but could use more work in future.
- Removes SVN cruft, including the post-commit hooks (in favour of the GitHub IRC bot) and the junk in Buildbot to support git-svn
- Removes historical cruft, including a lot of stuff in t-web -- this may be of historical interest (cc @glyph, @tomprince ?) but I do not believe it makes sense to have it where it is, so we can rescue it from the Git history
- Cleans up deployment to use virtualenvs instead of pip 'user' mode, meaning that our Twisted version is independent to what the distro ships. PyPy 4.0.1 is also included.
- Makes it work on Ubuntu 14.04, the most recent LTS
- Removes a lot of junk from t-web and other modules that wasn't needed.

### CODE REVIEW

**Comment by glyph** [comment]
"Sorry, we could not display this diff because it was too big".

I really hope that this is destined to be broken into a LOT of smaller PRs...

**Comment by hawkowl** [comment]
@glyph yeah, I'm just not sure how we're going to merge piecemeal without breaking current master. I guess a staging branch will work fine?

**Comment by hawkowl** [comment]
first PR, broken up https://github.com/twisted-infra/braid/pull/180

**Comment by hawkowl** [comment]
Second PR, broken up #181

**Comment by adiroiban** [comment]
can you add some notes about how to review / check this branch ?

Is this supposed to be applied on the Vangrant VM ? 

I was hoping that we can have a staging.twistedmatrix.com public facing system on which we can apply this state and have it integrated with GitHub

Is this documented somehwere?

Thanks!

**Comment by hawkowl** [comment]
This is being broken up into many more smaller branches.

**Pull request closed without merging**
