### PR TITLE
Add valid login URL.

### PR DESCRIPTION
**Pull request by adiroiban**
I hope that this fixed the invalid login URL.

I am not sure how to deploy this.

I hope someone will know how to push this in production.

### CODE REVIEW

**Comment by rodrigc** [comment]
If I look at this line where `You are currently not logged in. You may want to do so now.` is printed:

https://github.com/edgewall/trac/blob/974f08d0052bda990c173c687b67dd489d53b70a/trac/web/main.py#L679

I think this config change will fix the issue where the link is wrong.

**Comment by glyph** [comment]
Hmm. I've deployed this (`fab config.production trac.update`) but it doesn't seem fixed.

**Comment by glyph** [comment]
Hmm. Reading this code, I think that we need a redirect from `/trac/login` directly: it seems like `.login()` literally means the string, `"login"`, in the URL:

```
>>> trac.web.href.Href('/trac/').login()
'/trac/login'
```

**Comment by glyph** [comment]
Hmm. Reading this code, I think that we need a redirect from `/trac/login` directly: it seems like `login`

```
>>> trac.web.href.Href('/trac/').login()
'/trac/login'
```

**Comment by glyph** [comment]
Erm, okay, well… I fixed it, so I guess I lied about not having the time to look at this.  But the way I fixed it was extremely gross and weird because I have *NO* idea what's going on in `~t-web/config`; nominally this is deployed via braid, but the `twisted-web` service that got migrated over to `Braid` when we stopped using submodules does not even bear a *passing* resemblance to what's actually on the server, its git remote still points at https://github.com/twisted-infra/t-web even though that says "disused", and there are tons of modified files in the working copy that aren't checked in anywhere.

**Comment by rodrigc** [comment]
Thanks for fixing, @glyph, I can confirm that at https://twistedmatrix.com/trac/newticket , the `do so` link now points to the correct URL.
That's a bit unfortunate that there are some configs on the running system that are not checked into git, but that's OK.

**Comment by adiroiban** [comment]
I am worried that Trac deployment is not in Braid. Also I don't know what backups do we have.
This means that if we somehow lost the VM, we might loose the whole Trac info.

I remember that when migrating Trac tickets to GitHub issues was proposed a few years ago, this was blocked as some data from Trac would be lost.

With the current time that Twisted developers have to keep the Twisted infrastructure, I think is best to migrate the tickets to GitHub Issues.
GitHub Issues was a bad product 4 years ago, but it is getting better.

**Comment by glyph** [comment]
Our hosting provider, tummy.com, maintains regular whole-system backups, so data loss is not a concern. (We have recovered from these more than once with little disruption to availability.)

Definitely agreed on the concern with not having the t-web deployment in braid.  (The trac service itself is mostly accurate within braid, however.)

**Comment by glyph** [comment]
(Also, dornkirk is not a VM, it's physical hardware)

**Pull request merged**
