### PR TITLE
Some simple Python 3 fixes

### PR DESCRIPTION
**Pull request by rodrigc**

### CODE REVIEW

**Comment by rodrigc** [comment]
@adiroiban Can you review this?

**Comment by adiroiban** [comment]
looks good. thanks!

changes-approved

**Comment by rodrigc** [comment]
@hawkowl @adiroiban @glyph Can someone merge this?  I can't do it on this repository.
Thanks.

**Comment by rodrigc** [comment]
Thanks @adiroiban !  I don't know what the procedures are for merging to braid either.
 I'm going to assume that as long as the change is reviewed by a braid member, and it isn't too bad, it should be OK.

Thanks!

**Comment by adiroiban** [comment]
The past merged were "dirty".  Not many PR and not many reviews.

As long as there is a PR and a review , it is well above the existing practices.

See if you can use the GitHub merge button, and feel free to merge.

Thanks!

**Pull request merged**
