### PR TITLE
Get Trac+Kenaan working in the staging infra

### PR DESCRIPTION
**Pull request by hawkowl**

### CODE REVIEW

**Comment by hawkowl** [comment]
To test this:

```
vagrant up
fab config.vagrant base.bootstrap
fab config.vagrant t-web.install
fab config.vagrant t-web.makeTestTLSKeys
fab config.vagrant t-web.installSSLKeys
fab config.vagrant trac.install
fab config.vagrant trac.installTestData
fab config.vagrant amptrac.install
fab config.vagrant kenaan.install
fab config.vagrant t-web.start
fab config.vagrant trac.start
fab config.vagrant amptrac.start
fab config.vagrant kenaan.start
```

Then add 172.16.255.140 twistedmatrix.com in your hosts file and register an account. I haven't got the spam filter tables making themselves yet, so you can't make tickets.

**Comment by hawkowl** [comment]
I tested this locally with these additional commands:

```
fab config.production trac.dump:prod.dump.tar.gz,False
fab config.vagrant trac.restore:prod.dump.tar.gz,True,False
```

This will download prod's database, and restore it into the Vagrant VM (without any attachments). Then if you do:

```
fab config.vagrant trac.restart
```

...you can log in and look around.

**Comment by glyph** [comment]
Trying to turn these instructions into a shell script, I noticed that you need ansible installed first.

**Comment by glyph** [comment]
I also can't authenticate to `trac`.

**Comment by glyph** [comment]
```
$ fab config.vagrant trac.restart
[172.16.255.140] Executing task 'trac.restart'
[172.16.255.140] run: ~/bin/stop
[172.16.255.140] Passphrase for private key: 
```

**Pull request merged**
